name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.pur3um }}
          TIMEZONE: Asia/Seoul
